import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import {
  BrandKitSchema,
  ContentManifestSchema,
  DesignTokensSchema,
  RunConfigSchema,
  ScreenTreeSchema,
} from "../packages/harness/src/types.js";
import { HarnessConfigSchema } from "../packages/harness/src/harness-config.js";

type AnySchema = {
  def?: Record<string, unknown>;
  _def?: Record<string, unknown>;
  description?: string;
  shape?: Record<string, AnySchema>;
  options?: unknown[];
};

type Row = {
  field: string;
  type: string;
  required: string;
  defaultValue: string;
  description: string;
};

const outPath = resolve("docs", "inputs.md");
const check = process.argv.includes("--check");

const sections: Array<{ file: string; schema?: AnySchema; rows?: Row[]; note?: string }> = [
  { file: "content.json", schema: ContentManifestSchema as unknown as AnySchema },
  { file: "brand.json", schema: BrandKitSchema as unknown as AnySchema },
  { file: "screens.json", schema: ScreenTreeSchema as unknown as AnySchema },
  { file: "design.json", schema: DesignTokensSchema as unknown as AnySchema },
  { file: "run.json", schema: RunConfigSchema as unknown as AnySchema },
  { file: "harness.config.json", schema: HarnessConfigSchema as unknown as AnySchema },
  {
    file: "prompt.txt",
    rows: [{ field: "body", type: "string", required: "yes", defaultValue: "", description: "Free-form build brief injected into every run." }],
  },
  {
    file: "fetch-content.js",
    note: "Optional example helper script. It is not parsed by the harness; examples may use it to prepare or refresh JSON inputs.",
    rows: [{ field: "script", type: "JavaScript", required: "no", defaultValue: "", description: "Project-local content preparation helper." }],
  },
];

function main(): void {
  const markdown = render();
  if (check) {
    const current = existsSync(outPath) ? readFileSync(outPath, "utf-8") : "";
    if (current !== markdown) {
      console.error("docs/inputs.md is out of date. Run: npx tsx scripts/gen-input-docs.ts");
      process.exit(1);
    }
    return;
  }
  writeFileSync(outPath, markdown);
}

function render(): string {
  const lines = [
    "# Input Reference",
    "",
    "Generated from the Zod schemas in `packages/harness/src/types.ts` and `packages/harness/src/harness-config.ts`.",
    "Do not edit this file by hand; run `npx tsx scripts/gen-input-docs.ts`.",
    "",
  ];

  for (const section of sections) {
    const rows = section.rows ?? flattenObject(section.schema!, section.file);
    lines.push(`## ${section.file}`, "");
    if (section.note) lines.push(section.note, "");
    lines.push("| Field | Type | Required | Default | Description |");
    lines.push("| --- | --- | --- | --- | --- |");
    for (const row of rows) {
      lines.push(`| \`${row.field}\` | ${escapeCell(row.type)} | ${row.required} | ${escapeCell(row.defaultValue)} | ${escapeCell(row.description)} |`);
    }
    lines.push("");
  }

  return `${lines.join("\n")}\n`;
}

function flattenObject(schema: AnySchema, file: string): Row[] {
  const shape = objectShape(schema);
  return Object.entries(shape).flatMap(([name, child]) => flattenField(name, child, file));
}

function flattenField(path: string, schema: AnySchema, file: string, inheritedRequired = true, depth = 0): Row[] {
  const info = schemaInfo(schema);
  const description = schema.description ?? info.schema.description ?? "";
  const row: Row = {
    field: path,
    type: schemaType(info.schema),
    required: inheritedRequired && info.required ? "yes" : "no",
    defaultValue: info.defaultValue,
    description: description || "No description provided.",
  };

  if (depth > 3) return [row];

  if (isObject(info.schema)) {
    return [
      row,
      ...Object.entries(objectShape(info.schema)).flatMap(([name, child]) =>
        flattenField(`${path}.${name}`, child, file, inheritedRequired && info.required, depth + 1)
      ),
    ];
  }

  const arrayItem = arrayElement(info.schema);
  if (arrayItem && isObject(arrayItem)) {
    if (path.includes("children")) return [row];
    return [
      row,
      ...Object.entries(objectShape(arrayItem)).flatMap(([name, child]) =>
        flattenField(`${path}[].${name}`, child, file, inheritedRequired && info.required, depth + 1)
      ),
    ];
  }

  if (file === "harness.config.json" && path.endsWith("verify")) {
    return [row, verifySummaryRow(`${path}[]`)];
  }

  return [row];
}

function schemaInfo(schema: AnySchema): { schema: AnySchema; required: boolean; defaultValue: string } {
  let current = schema;
  let required = true;
  let defaultValue = "";

  for (;;) {
    const d = def(current);
    if (d.type === "default") {
      required = false;
      defaultValue = formatDefault((d as { defaultValue?: unknown }).defaultValue);
      current = d.innerType as AnySchema;
    } else if (d.type === "optional") {
      required = false;
      current = d.innerType as AnySchema;
    } else if (d.type === "nullable") {
      required = false;
      current = d.innerType as AnySchema;
    } else {
      return { schema: current, required, defaultValue };
    }
  }
}

function schemaType(schema: AnySchema): string {
  const d = def(schema);
  if (d.type === "string" || d.type === "number" || d.type === "boolean") return String(d.type);
  if (d.type === "literal") return JSON.stringify((d as { values?: unknown[] }).values?.[0] ?? (d as { value?: unknown }).value);
  if (d.type === "enum") return Object.keys((d as { entries?: Record<string, string> }).entries ?? {}).map((v) => `\`${v}\``).join(" | ");
  if (d.type === "array") {
    const inner = schemaType((d as { element: AnySchema }).element);
    return inner.includes("|") ? `(${inner})[]` : `${inner}[]`;
  }
  if (d.type === "object") return "object";
  if (d.type === "union") return "union";
  if (d.type === "pipe") return schemaType((d as { in: AnySchema }).in);
  if (d.type === "lazy") return "object";
  return String(d.type ?? "unknown");
}

function objectShape(schema: AnySchema): Record<string, AnySchema> {
  const d = def(schema);
  if (d.type === "lazy") return objectShape((schema as unknown as { unwrap: () => AnySchema }).unwrap());
  return (d.shape ?? schema.shape ?? {}) as Record<string, AnySchema>;
}

function isObject(schema: AnySchema): boolean {
  const d = def(schema);
  return d.type === "object" || d.type === "lazy";
}

function arrayElement(schema: AnySchema): AnySchema | null {
  const d = def(schema);
  return d.type === "array" ? (d.element as AnySchema) : null;
}

function def(schema: AnySchema): Record<string, unknown> {
  return schema.def ?? schema._def ?? {};
}

function formatDefault(value: unknown): string {
  if (typeof value === "function") return formatDefault(value());
  if (value === undefined) return "";
  return typeof value === "string" ? value : JSON.stringify(value);
}

function verifySummaryRow(field: string): Row {
  return {
    field,
    type: "`file_exists` | `grep` | `git_dirty` | `tsc` | `focus_check` | `forbidden_import` | `command`",
    required: "no",
    defaultValue: "",
    description: "Declarative check from `VerifyCheckSchema`; each variant has a `type` and optional `error`.",
  };
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

main();
